### ISSUE TITLE
Vertical Menu

### ISSUE THREAD

**Issue by MohammedMir** [ahmedragab/WheelComponent#1]
Hi,

I have to modify this component for one of my projects, where I have to show vertical infinite scroll menu and in this menu at least 5 items must be visible one after another and the centre one has to be little bit enlarged. Could you please suggest me which part of the code is to be modified to meet that requirement.

Regards
Mohammed

**Comment by ahmedragab** [comment]
set the height of the wheel view and the hight of each cell in the view controller to show 5 items. by default the centre cell is enlarged. Infinite scrolling is not handled but you need to handle it in the view to catch when the scrolling reach the last item then notify the controller to refresh items count
